# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='pytorch.elf.game.v1',
  syntax='proto3',
  serialized_pb=_b('\n\ngame.proto\x12\x13pytorch.elf.game.v1\x1a\x17google/rpc/status.proto\"\x14\n\x04\x42\x65\x61t\x12\x0c\n\x04\x62\x65\x61t\x18\x01 \x01(\x05\"\x1e\n\tBeatReply\x12\x11\n\tbeatReply\x18\x01 \x01(\x05\"\x14\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"v\n\x04Step\x12+\n\x06player\x18\x01 \x01(\x0b\x32\x1b.pytorch.elf.game.v1.Player\x12\x33\n\ncoordinate\x18\x02 \x01(\x0b\x32\x1f.pytorch.elf.game.v1.Coordinate\x12\x0c\n\x04move\x18\x03 \x01(\t\"\xbe\x01\n\x05Reply\x12\x33\n\ncoordinate\x18\x01 \x01(\x0b\x32\x1f.pytorch.elf.game.v1.Coordinate\x12\x13\n\x0bnext_player\x18\x02 \x01(\t\x12\x13\n\x0b\x66inal_score\x18\x03 \x01(\x02\x12\"\n\x06status\x18\x04 \x01(\x0b\x32\x12.google.rpc.Status\x12\x10\n\x08resigned\x18\x05 \x01(\x08\x12\x11\n\tlast_move\x18\x06 \x01(\t\x12\r\n\x05\x62oard\x18\x07 \x01(\t2\x89\x04\n\x04Game\x12\x38\n\x05NewGC\x12\x1b.pytorch.elf.game.v1.Player\x1a\x12.google.rpc.Status\x12\x39\n\x06\x46reeGC\x12\x1b.pytorch.elf.game.v1.Player\x1a\x12.google.rpc.Status\x12=\n\nClearBoard\x12\x1b.pytorch.elf.game.v1.Player\x1a\x12.google.rpc.Status\x12=\n\x04Play\x12\x19.pytorch.elf.game.v1.Step\x1a\x1a.pytorch.elf.game.v1.Reply\x12\x42\n\x07GenMove\x12\x1b.pytorch.elf.game.v1.Player\x1a\x1a.pytorch.elf.game.v1.Reply\x12?\n\x04Pass\x12\x1b.pytorch.elf.game.v1.Player\x1a\x1a.pytorch.elf.game.v1.Reply\x12\x41\n\x06Resign\x12\x1b.pytorch.elf.game.v1.Player\x1a\x1a.pytorch.elf.game.v1.Reply\x12\x46\n\tHeartBeat\x12\x19.pytorch.elf.game.v1.Beat\x1a\x1e.pytorch.elf.game.v1.BeatReplyB\tZ\x07\x65lfgameb\x06proto3')
  ,
  dependencies=[google_dot_rpc_dot_status__pb2.DESCRIPTOR,])




_BEAT = _descriptor.Descriptor(
  name='Beat',
  full_name='pytorch.elf.game.v1.Beat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beat', full_name='pytorch.elf.game.v1.Beat.beat', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=80,
)


_BEATREPLY = _descriptor.Descriptor(
  name='BeatReply',
  full_name='pytorch.elf.game.v1.BeatReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beatReply', full_name='pytorch.elf.game.v1.BeatReply.beatReply', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=112,
)


_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='pytorch.elf.game.v1.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pytorch.elf.game.v1.Player.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=134,
)


_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='pytorch.elf.game.v1.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='pytorch.elf.game.v1.Coordinate.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='pytorch.elf.game.v1.Coordinate.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=170,
)


_STEP = _descriptor.Descriptor(
  name='Step',
  full_name='pytorch.elf.game.v1.Step',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='pytorch.elf.game.v1.Step.player', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='pytorch.elf.game.v1.Step.coordinate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move', full_name='pytorch.elf.game.v1.Step.move', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=290,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='pytorch.elf.game.v1.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='pytorch.elf.game.v1.Reply.coordinate', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_player', full_name='pytorch.elf.game.v1.Reply.next_player', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='final_score', full_name='pytorch.elf.game.v1.Reply.final_score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='pytorch.elf.game.v1.Reply.status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resigned', full_name='pytorch.elf.game.v1.Reply.resigned', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_move', full_name='pytorch.elf.game.v1.Reply.last_move', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='board', full_name='pytorch.elf.game.v1.Reply.board', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=483,
)

_STEP.fields_by_name['player'].message_type = _PLAYER
_STEP.fields_by_name['coordinate'].message_type = _COORDINATE
_REPLY.fields_by_name['coordinate'].message_type = _COORDINATE
_REPLY.fields_by_name['status'].message_type = google_dot_rpc_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['Beat'] = _BEAT
DESCRIPTOR.message_types_by_name['BeatReply'] = _BEATREPLY
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Coordinate'] = _COORDINATE
DESCRIPTOR.message_types_by_name['Step'] = _STEP
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Beat = _reflection.GeneratedProtocolMessageType('Beat', (_message.Message,), dict(
  DESCRIPTOR = _BEAT,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:pytorch.elf.game.v1.Beat)
  ))
_sym_db.RegisterMessage(Beat)

BeatReply = _reflection.GeneratedProtocolMessageType('BeatReply', (_message.Message,), dict(
  DESCRIPTOR = _BEATREPLY,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:pytorch.elf.game.v1.BeatReply)
  ))
_sym_db.RegisterMessage(BeatReply)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
  DESCRIPTOR = _PLAYER,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:pytorch.elf.game.v1.Player)
  ))
_sym_db.RegisterMessage(Player)

Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATE,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:pytorch.elf.game.v1.Coordinate)
  ))
_sym_db.RegisterMessage(Coordinate)

Step = _reflection.GeneratedProtocolMessageType('Step', (_message.Message,), dict(
  DESCRIPTOR = _STEP,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:pytorch.elf.game.v1.Step)
  ))
_sym_db.RegisterMessage(Step)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:pytorch.elf.game.v1.Reply)
  ))
_sym_db.RegisterMessage(Reply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\007elfgame'))

_GAME = _descriptor.ServiceDescriptor(
  name='Game',
  full_name='pytorch.elf.game.v1.Game',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=486,
  serialized_end=1007,
  methods=[
  _descriptor.MethodDescriptor(
    name='NewGC',
    full_name='pytorch.elf.game.v1.Game.NewGC',
    index=0,
    containing_service=None,
    input_type=_PLAYER,
    output_type=google_dot_rpc_dot_status__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FreeGC',
    full_name='pytorch.elf.game.v1.Game.FreeGC',
    index=1,
    containing_service=None,
    input_type=_PLAYER,
    output_type=google_dot_rpc_dot_status__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ClearBoard',
    full_name='pytorch.elf.game.v1.Game.ClearBoard',
    index=2,
    containing_service=None,
    input_type=_PLAYER,
    output_type=google_dot_rpc_dot_status__pb2._STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Play',
    full_name='pytorch.elf.game.v1.Game.Play',
    index=3,
    containing_service=None,
    input_type=_STEP,
    output_type=_REPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GenMove',
    full_name='pytorch.elf.game.v1.Game.GenMove',
    index=4,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_REPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Pass',
    full_name='pytorch.elf.game.v1.Game.Pass',
    index=5,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_REPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Resign',
    full_name='pytorch.elf.game.v1.Game.Resign',
    index=6,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_REPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HeartBeat',
    full_name='pytorch.elf.game.v1.Game.HeartBeat',
    index=7,
    containing_service=None,
    input_type=_BEAT,
    output_type=_BEATREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAME)

DESCRIPTOR.services_by_name['Game'] = _GAME

# @@protoc_insertion_point(module_scope)
